# Copyright 2021 Agnostiq Inc.
#
# This file is part of Covalent.
#
# Licensed under the GNU Affero General Public License 3.0 (the "License").
# A copy of the License may be obtained with this software package or at
#
#      https://www.gnu.org/licenses/agpl-3.0.en.html
#
# Use of this file is prohibited except in compliance with the License. Any
# modifications or derivative works of this file must retain this copyright
# notice, and modified files must contain a notice indicating that they have
# been altered from the originals.
#
# Covalent is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the License for more details.
#
# Relief from the License may be granted by purchasing a commercial license.

{% set name = "cova" %}
{% set version = "0.22.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cova-{{ version }}.1.tar.gz
    sha256: 1e8f4dd144905b71eb228dda90a99d60d16bc7f6f40a997f70416347a362ee4f
  - url: https://files.pythonhosted.org/packages/5b/78/0c8e4b41ee425be92888bc118af7c15fc7b771a7e495d7b48b223cd6c382/sentinel-0.3.0.tar.gz
    sha256: f28143aa4716dbc8f6193f5682176a3c33cd26aaae05d9ecf66c186a9887cc2d
    folder: sentinel
    
build:
  skip: true  # [win]
  skip: true  # [osx]
  entry_points:
    - covalent = covalent_dispatcher._cli.cli:cli
  #noarch: python
  script:
    - pip install ./sentinel
    - pip install . -vv

  number: 0

requirements:
  host:
    - pip
    #- python >=3.8
    - python
    - poetry
  run:
    - cloudpickle ==2.0.0
    - dask-core ==2021.10.0
    - eventlet ==0.30.2
    - flask ==2.0.1
    - flask-cors ==3.0.10
    - flask-socketio ==5.1.1
    - gunicorn ==20.1.0
    - matplotlib-base ==3.3.1
    - networkx ==2.5
    #- python >=3.8
    - python
    - requests ==2.24.0
    - simplejson ==3.17.6
    - tailer ==0.4.1
    - toml ==0.10.2
    #- distributed ==2021.10.0
    - distributed

test:
  imports:
    - covalent
    - covalent_dispatcher
    - covalent_ui
  commands:
    - pip check
    - covalent --help
    - covalent status
  requires:
    - pip

about:
  home: https://github.com/AgnostiqHQ/covalent
  summary: Covalent Workflow Tool
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AgnostiqHQ
