{% set name = "cova" %}
{% set version = "0.22.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cova-{{ version }}.1.tar.gz
    sha256: 1e8f4dd144905b71eb228dda90a99d60d16bc7f6f40a997f70416347a362ee4f
    
build:
  skip: true  # [win]
  skip: true  # [osx]
  entry_points:
    - covalent = covalent_dispatcher._cli.cli:cli
  script:
    - pip install . -vv

  number: 0

requirements:
  host:
    - pip
    - python 3.8
    - poetry
  run:
    - cloudpickle ==2.0.0
    - dask-core ==2021.10.0
    - eventlet ==0.30.2
    - flask ==2.0.1
    - flask-cors ==3.0.10
    - flask-socketio ==5.1.1
    - gunicorn ==20.1.0
    - matplotlib-base ==3.3.1
    - networkx ==2.5
    - python 3.8
    - requests ==2.24.0
    - sentinel ==0.3.0
    - simplejson ==3.17.6
    - tailer ==0.4.1
    - toml ==0.10.2
    - distributed ==2021.10.0

test:
  imports:
    - covalent
    - covalent_dispatcher
    - covalent_ui
  commands:
    - pip check
    - covalent --help
    - covalent status
  requires:
    - pip

about:
  home: https://github.com/AgnostiqHQ/covalent
  summary: Covalent Workflow Tool
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AgnostiqHQ
