{% set name = "cova" %}
{% set version = "0.27.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cova-{{ version }}.tar.gz
    sha256: 79c72a4561f1dad66c44835b4a7e5cbf5c1054835702e7e67b1efd085ef5fe9b
    
build:
  skip: true  # [win]
  skip: true  # [osx]
  entry_points:
    - covalent = covalent_dispatcher._cli.cli:cli
  script:
    - pip install . -vv

  number: 0

requirements:
  host:
    - pip
    - python 3.8
    - poetry
  run:
    - cloudpickle ==2.0.0
    - dask[distributed] ==2022.1.0
    - eventlet ==0.30.2
    - flask ==2.0.1
    - flask-cors ==3.0.10
    - flask-socketio ==5.1.1
    - gunicorn ==20.1.0
    - matplotlib ==3.5.1
    - networkx ==2.5
    - python 3.8
    - requests ==2.24.0
    - simplejson ==3.17.6
    - tailer ==0.4.1
    - toml ==0.10.2

test:
  imports:
    - covalent
    - covalent_dispatcher
    - covalent_ui
  commands:
    - pip check
    - covalent --help
    - covalent status
  requires:
    - pip

about:
  home: https://github.com/AgnostiqHQ/covalent
  summary: Covalent Workflow Tool
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jkanem
    - wjcunningham7
